name: golang_apps
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/common-setup

    - name: Copy script to run recipes
      run: cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/covid_app_recipe.txt /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/foodpalaceapp_recipe.txt /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/niovakv_recipes.txt /home/runner/work/niovad/niovad/build_dir/

    - name:  run recipe for covid application
      run:  export GOCOVERDIR=/home/runner/work/niovad/niovad/code_cov &&
          cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/covid_app_recipe.txt'
                             'covid'
                             '0'
                             '0'
                             '/home/runner/work/go/go/bin'

    - name:  run recipe for foodpalace application
      run: export GOCOVERDIR=/home/runner/work/niovad/niovad/code_cov &&
           cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/foodpalaceapp_recipe.txt'
                             'foodpalace'
                             '0'
                             '0'
                             '/home/runner/work/go/go/bin'

    - name:  run recipes for niovakv application
      run: export GOCOVERDIR=/home/runner/work/niovad/niovad/code_cov &&
           cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/niovakv_recipes.txt'
                             'niovakv'
                             '0'
                             '0'
                             '/home/runner/work/go/go/bin'

    - uses: ./.github/actions/teardown-success
#      if: ${{ !failure() }}

    - uses: ./.github/actions/teardown-failure
      if: failure() # run teardown regardless of failure
