name: failover
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/common-setup/action.yml

    - name: Copy script to run recipes
      run: cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/failover_recipes.txt /home/runner/work/niovad/niovad/build_dir/

    - name:  run recipes
      run: cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/failover_recipes.txt'
                             'pumicedb'
                             '/home/runner/work/go/go/bin'

    - uses: ./.github/actions/teardown-success
#      if: ${{ !failure() }}

    - uses: ./.github/actions/teardown-failure
      if: failure() # run teardown regardless of failure
