name: holon_coalesced_wr_recipes_workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: apt update
      run: sudo apt update

    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0
  
    # Install golang
    - name: Install golang 1.20.3
      run: sudo rm -rf /usr/bin/go &&
           sudo wget https://golang.org/dl/go1.20.3.linux-amd64.tar.gz &&
           sudo mkdir /home/runner/work/go &&
           sudo tar -C /home/runner/work/go -xzf  go1.20.3.linux-amd64.tar.gz &&
           export PATH=$PATH:/home/runner/work/go/go/bin &&
           go version

    - name: Install python libraries
      run:  pip3 install setuptools wheel func_timeout sockets psutil dpath jmespath

      # Install Ansible
    - name: Install Ansible
      run:  pip3 install ansible==9.2

    - name: build libbacktrace
      run: cd modules/libbacktrace/ && ./configure && make && sudo make install

    - name: Build niova-core for niova-raft
      run: cd modules/niova-raft/modules/niova-core/ && 
           ./prepare.sh &&
           ./configure --enable-devel --prefix=/home/runner/work/niovad/niovad/build_dir/ && 
           make -j 4 && 
           make -j 4 check && 
           make install

    - name: build niova-raft
      run: cd modules/niova-raft && 
            ./prepare.sh &&
            ./configure --enable-devel --prefix=/home/runner/work/niovad/niovad/build_dir/ --with-niova=/home/runner/work/niovad/niovad/build_dir/ &&
            make -j 4 && 
            make -j 4 check && 
            make install

    - name: make
      run: ./prepare.sh &&
           ./configure --with-niova=/home/runner/work/niovad/niovad/build_dir/ --prefix=/home/runner/work/niovad/niovad/build_dir/ --enable-devel &&
           make clean && make && make install
      env:
        LD_LIBRARY_PATH: /home/runner/work/niovad/niovad/build_dir/lib

    - name: Copy script to run recipes
      run: cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/coalesced_wr_recipes.txt /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/coalesced_wr_recipes_with_sync.txt /home/runner/work/niovad/niovad/build_dir/

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
       repository: 00pauln00/holon
      #  ref: 
       path: ./holon

    - name: Copy holon repo
      run: cp -r ./holon /home/runner/work/niovad/niovad/build_dir/

    - name: Create log directory for storing holon logs
      run: mkdir  /home/runner/work/niovad/niovad/holon_log

    - name: list recipes
      run: ls -ltr /home/runner/work/niovad/niovad/build_dir

    - name:  run recipes
      run: cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/coalesced_wr_recipes.txt'
                             'pumicedb'
                             '1'
                             '0'
                             '/home/runner/work/go/go/bin'

    - name:  run coalesced recipes with sync mode
      run: cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/coalesced_wr_recipes_with_sync.txt'
                             'pumicedb'
                             '1'
                             '1'
                             '/home/runner/work/go/go/bin'

    - name: Prepare artifact filename
      id: prepare_artifact_filename
      run: |
        echo ::set-output name=ARTIFACT_NAME::test-recipe-report_${{ github.event.pull_request.head.sha }}_${{ github.run_attempt }}
      if: failure()

    - name: Archive the test results
      uses: actions/upload-artifact@v4
      with:
         name: ${{ steps.prepare_artifact_filename.outputs.ARTIFACT_NAME }}
         path: /home/runner/work/niovad/niovad/holon_log
      if: failure()
