name: holon_basic_recipes_workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run: sudo apt update
    - name: dpkg / rpm prep (debug)
      run: echo "sudo -E apt-get install -y uuid-dev uuid libuuid1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0"
    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0

# capture gcc and clang versions
    - name: gcc version
      run: gcc --version
    - name: clang version
      run: clang --version

# Install Ansible
    - name: Install Ansible
      run:  pip3 install ansible

# build backtrace submodule
    - name: submodule init
      run: git submodule init && git submodule update

# build backtrace submodule
    - name: build libbacktrace
      run: cd modules/libbacktrace/ && ./configure && make && sudo make install

# niova-core submodule init
    - name: submodule init (niova-core)
      run: cd modules/niova-core && git submodule init && git submodule update

# build niova-core
    - name: build niova-core
      run: git submodule update && cd modules/niova-core/ && ./prepare.sh &&
        ./configure --enable-devel --prefix=/usr/local/niova &&
        make -j 4 && make -j 4 check && sudo make install

#build niova-raft
    - name: Checkout niova-raft
      uses: actions/checkout@v4
      with:
        repository: 00pauln00/niova-raft
        ref: niova_repo_split
        path: ./niova-raft

    - name: Compile niova-raft
      run: cd ./niova-raft && ./prepare.sh && ./configure LDFLAGS=-L/usr/local/lib --with-niova=/usr/local/niova --prefix=/usr/local/niova --enable-asan --enable-devel && make clean && make && make install


    - name: Install python libraries
      run:  pip3 install setuptools wheel func_timeout sockets psutil dpath jmespath

# default build
    - name: prepare default build
      run: ./prepare.sh
    - name: configure
      run: ./configure LDFLAGS=-L/usr/local/lib --with-niova=/usr/local/niova --prefix=/home/runner/work/niovad/niovad/build_dir/ --enable-asan --enable-devel && make clean && make && make install
      env:
        LD_LIBRARY_PATH: /home/runner/work/niovad/niovad/build_dir/lib


    - name: Copy script to run recipes
      run: cp ./scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp ./scripts/basic_recipes.txt /home/runner/work/niovad/niovad/build_dir/

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
       repository: 00pauln00/holon
       #ref:
       token: ${{ secrets.HOLON_NIOVA_CI_21_12_2020 }} # 'GitHub_PAT' is a secret that contains your PAT
       path: ./holon

    - name: Copy holon repo
      run: cp -r ./holon /home/runner/work/niovad/niovad/build_dir/

    - name: Create log directory for storing holon logs
      run: mkdir  /home/runner/work/niovad/niovad/holon_log

    - name:  run recipes
      run: cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/basic_recipes.txt'
                             'raft'
                             '/home/runner/work/go/go/bin'


    - name: Prepare artifact filename
      id: prepare_artifact_filename
      run: |
        echo ::set-output name=ARTIFACT_NAME::test-recipe-report_${{ github.event.pull_request.head.sha }}_${{ github.run_attempt }}
      if: failure()

    - name: Archive the test results
      uses: actions/upload-artifact@v4
      with:
         name: ${{ steps.prepare_artifact_filename.outputs.ARTIFACT_NAME }}
         path: /home/runner/work/niovad/niovad/holon_log
      if: failure()
